backend:
  name: git-gateway
  branch: netlify

media_folder: "content/uploads"
public_folder: "/content/uploads"

collections:
  - name: "daily-timeblocks"
    label: "Daily Timeblocks"
    format: "json"
    extension: "json"
    folder: "content/daily-timeblocks/json"
    identifier_field: dateString
    delete: false
    create: false
    fields:
      - { label: "Date String", name: "dateString", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }

  - name: "articles"
    label: "Articles"
    format: "json"
    extension: "json"
    folder: "content/articles/json"
    identifier_field: slug
    delete: false
    create: false
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date Created", name: "date-created", widget: "datetime" }
      - { label: "Content", name: "content", widget: "markdown" }

  - name: "task-list-snapshots"
    label: "Task List Snapshots"
    format: "json"
    extension: "json"
    folder: "content/task-list-snapshots/json"
    identifier_field: dateString
    delete: false
    create: false
    fields:
      - label: "Date String"
        name: "dateString"
        widget: "string"

      - label: "Tasks"
        name: "tasks"
        widget: "markdown"

        fields:
          - name: "Description"
            label: "description"
            widget: "string"

          - name: "Completed"
            label: "completed"
            widget: "boolean"

          - name: "Deadline"
            label: "deadline"
            widget: "string"

          - name: "Deadline Notes"
            label: "deadline-notes"
            widget: "string"
