backend:
  name: git-gateway
  branch: netlify

media_folder: "content/uploads"
public_folder: "/content/uploads"

collections:
  - name: "daily-timeblocks"
    label: "Daily Timeblocks"
    format: "json"
    extension: "json"
    folder: "content/daily-timeblocks/json"
    slug: "{{year}}-{{month}}-{{day}}"
    identifier_field: date-string
    delete: false
    create: false
    fields:
      - { label: "Date String", name: "date-string", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Daily Plans", name: "daily-plans", widget: "markdown" }
      - {
          label: "Quarterly Plans",
          name: "quarterly-plans",
          widget: "markdown",
        }
      - { label: "Thoughts", name: "thoughts", widget: "markdown" }
      - { label: "Timeblocks", name: "timeblocks", widget: "markdown" }
      - { label: "Weekly Plans", name: "weekly-plans", widget: "markdown" }

  - name: "articles"
    label: "Articles"
    format: "json"
    extension: "json"
    folder: "content/articles/json"
    identifier_field: slug
    delete: false
    create: false
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date Created", name: "date-created", widget: "datetime" }
      - { label: "Content", name: "content", widget: "markdown" }

  - name: "task-list-snapshots"
    label: "Task List Snapshots"
    format: "json"
    extension: "json"
    folder: "content/task-list-snapshots/json"
    identifier_field: date-string
    delete: false
    create: false
    fields:
      - label: "Date String"
        name: "date-string"
        widget: "string"

      - label: "Tasks"
        name: "list"
        widget: "markdown"

        fields:
          - name: "Description"
            label: "description"
            widget: "string"

          - name: "Completed"
            label: "completed"
            widget: "boolean"

          - name: "Deadline"
            label: "deadline"
            widget: "string"

          - name: "Deadline Notes"
            label: "deadline-notes"
            widget: "string"
