backend:
  name: git-gateway
  branch: main

media_folder: "packages/website/public/cms-assets/uploads"
public_folder: "/cms-assets/uploads"

collections:
  - name: "daily-timeblock"
    label: "Daily Timeblock"
    folder: "packages/netlify-cms-assets/daily-timeblocks"
    slug: "{{year}}-{{month}}-{{day}}"
    identifier_field: datestring
    fields:
      - { label: "Date String", name: "datestring", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Daily Plans", name: "daily-plans", widget: "markdown" }
      - {
          label: "Quarterly Plans",
          name: "quarterly-plans",
          widget: "markdown",
        }
      - { label: "Thoughts", name: "thoughts", widget: "markdown" }
      - { label: "Timeblocks", name: "timeblocks", widget: "markdown" }
      - { label: "Weekly Plans", name: "weekly-plans", widget: "markdown" }
