name: Netlify Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16.x

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Use pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install dependencies and build frontend
        run: pnpm install && pnpm build:website

      - name: Deploy to Netlify 🚀
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: ./packages/website/dist
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
